/*	
	https://www.ign.com/wikis/animal-crossing-new-horizons/Fish_Guide:_Fish_List,_Sell_Price,_and_Fishing_Tips#Pop-eyed_Goldfish 
	https://www.ign.com/wikis/animal-crossing-new-horizons/Bug_Guide:_Bugs_List,_Sell_Price,_and_Bug_Catching_Tips#Yellow_Butterfly_.E2.9C.93
*/
INSERT INTO [acnh].[Critters]
( [critter_name], [critter_type], [sale_price], [location], [comment] )
VALUES 
( 'Bitterling', 'FISH', 900, 'River', '' ),
( 'Pale Chub', 'FISH', 160, 'River', '' ),
( 'Crucian Carp', 'FISH', 160, 'River', '' ),
( 'Dace', 'FISH', 240, 'River', '' ),
( 'Carp', 'FISH', 300, 'Pond', '' ),
( 'Koi', 'FISH', 4000, 'Pond', '' ),
( 'Goldfish', 'FISH', 1300, 'Pond', '' ),
( 'Pop-eyed Goldfish', 'FISH', 1300, 'Pond', '' ),
( 'Ranchu Goldfish', 'FISH', 4500, 'Pond', '' ),
( 'Killifish', 'FISH', 300, 'Pond', '' ),
( 'Crawfish', 'FISH', 200, 'Pond', '' ),
( 'Soft-shelled Turtle', 'FISH', 3750, 'River', '' ),
( 'Snapping Turtle', 'FISH', 5000, 'River', '' ),
( 'Tadpole', 'FISH', 100, 'Pond', '' ),
( 'Frog', 'FISH', 120, 'Pond', '' ),
( 'Freshwater Goby', 'FISH', 400, 'River', '' ),
( 'Loach', 'FISH', 400, 'River', '' ),
( 'Catfish', 'FISH', 800, 'Pond', '' ),
( 'Giant Snakehead', 'FISH', 5500, 'Pond', '' ),
( 'Bluegill', 'FISH', 180, 'River', '' ),
( 'Yellow Perch', 'FISH', 300, 'River', '' ),
( 'Black Bass', 'FISH', 400, 'River', '' ),
( 'Tilapia', 'FISH', 800, 'River', '' ),
( 'Pike', 'FISH', 1800, 'River', '' ),
( 'Pond Smelt', 'FISH', 0, '400', '' ),
( 'Sweetfish', 'FISH', 900, 'River', '' ),
( 'Cherry Salmon', 'FISH', 1000, 'River (Clifftop)', '' ),
( 'Char', 'FISH', 3800, 'River (Clifftop)', '' ),
( 'Golden Trout', 'FISH', 15000, 'River (Clifftop)', '' ),
( 'Stringfish', 'FISH', 15000, 'River (Clifftop)', '' ),
( 'Salmon', 'FISH', 700, 'River (Mouth)', '' ),
( 'King Salmon', 'FISH', 1800, 'River (Mouth)', '' ),
( 'Mitten Crab', 'FISH', 2000, 'River', '' ),
( 'Guppy', 'FISH', 1300, 'River', '' ),
( 'Nibble Fish', 'FISH', 1500, 'River', '' ),
( 'Angelfish', 'FISH', 3000, 'River', '' ),
( 'Betta', 'FISH', 2500, 'River', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),