/*	
	https://www.ign.com/wikis/animal-crossing-new-horizons/Fish_Guide:_Fish_List,_Sell_Price,_and_Fishing_Tips#Pop-eyed_Goldfish 
	https://www.ign.com/wikis/animal-crossing-new-horizons/Bug_Guide:_Bugs_List,_Sell_Price,_and_Bug_Catching_Tips#Yellow_Butterfly_.E2.9C.93
*/
INSERT INTO [acnh].[Critters]
( [critter_name], [critter_type], [sale_price], [location], [comment] )
VALUES 
( 'Bitterling', 'FISH', 900, 'River', '' ),
( 'Pale Chub', 'FISH', 160, 'River', '' ),
( 'Crucian Carp', 'FISH', 160, 'River', '' ),
( 'Dace', 'FISH', 240, 'River', '' ),
( 'Carp', 'FISH', 300, 'Pond', '' ),
( 'Koi', 'FISH', 4000, 'Pond', '' ),
( 'Goldfish', 'FISH', 1300, 'Pond', '' ),
( 'Pop-eyed Goldfish', 'FISH', 1300, 'Pond', '' ),
( 'Ranchu Goldfish', 'FISH', 4500, 'Pond', '' ),
( 'Killifish', 'FISH', 300, 'Pond', '' ),
( 'Crawfish', 'FISH', 200, 'Pond', '' ),
( 'Soft-shelled Turtle', 'FISH', 3750, 'River', '' ),
( 'Snapping Turtle', 'FISH', 5000, 'River', '' ),
( 'Tadpole', 'FISH', 100, 'Pond', '' ),
( 'Frog', 'FISH', 120, 'Pond', '' ),
( 'Freshwater Goby', 'FISH', 400, 'River', '' ),
( 'Loach', 'FISH', 400, 'River', '' ),
( 'Catfish', 'FISH', 800, 'Pond', '' ),
( 'Giant Snakehead', 'FISH', 5500, 'Pond', '' ),
( 'Bluegill', 'FISH', 180, 'River', '' ),
( 'Yellow Perch', 'FISH', 300, 'River', '' ),
( 'Black Bass', 'FISH', 400, 'River', '' ),
( 'Tilapia', 'FISH', 800, 'River', '' ),
( 'Pike', 'FISH', 1800, 'River', '' ),
( 'Pond Smelt', 'FISH', 0, '400', '' ),
( 'Sweetfish', 'FISH', 900, 'River', '' ),
( 'Cherry Salmon', 'FISH', 1000, 'River (Clifftop)', '' ),
( 'Char', 'FISH', 3800, 'River (Clifftop)', '' ),
( 'Golden Trout', 'FISH', 15000, 'River (Clifftop)', '' ),
( 'Stringfish', 'FISH', 15000, 'River (Clifftop)', '' ),
( 'Salmon', 'FISH', 700, 'River (Mouth)', '' ),
( 'King Salmon', 'FISH', 1800, 'River (Mouth)', '' ),
( 'Mitten Crab', 'FISH', 2000, 'River', '' ),
( 'Guppy', 'FISH', 1300, 'River', '' ),
( 'Nibble Fish', 'FISH', 1500, 'River', '' ),
( 'Angelfish', 'FISH', 3000, 'River', '' ),
( 'Betta', 'FISH', 2500, 'River', '' ),
( 'Neon Tetra', 'FISH', 500, 'River', '' ),
( 'Rainbowfish', 'FISH', 800, 'River', '' ),
( 'Piranha', 'FISH', 2500, 'River', '' ),
( 'Arowana', 'FISH', 10000, 'River', '' ),
( 'Dorado', 'FISH', 15000, 'River', '' ),
( 'Gar', 'FISH', 6000, 'Pond', '' ),
( 'Arapaima', 'FISH', 10000, 'River', '' ),
( 'Saddled Bichir', 'FISH', 4000, 'River', '' ),
( 'Sturgeon', 'FISH', 10000, 'River (Mouth)', '' ),
( 'Sea Butterfly', 'FISH', 1000, 'Sea', '' ),
( 'Seahorse', 'FISH', 1100, 'Sea', '' ),
( 'Clownfish', 'FISH', 650, 'Ocean', '' ),
( 'Sturgeonfish', 'FISH', 1000, 'Sea', '' ),
( 'Butterfly Fish', 'FISH', 1000, 'Sea', '' ),
( 'Napoleonfish', 'FISH', 10000, 'Sea', '' ),
( 'Zebra Turkeyfish', 'FISH', 500, 'Sea', '' ),
( 'Blowfish', 'FISH', 5000, 'Sea', '' ),
( 'Puffer Fish', 'FISH', 250, 'Sea', '' ),
( 'Anchovy', 'FISH', 200, 'Sea', '' ),
( 'Horse Mackerel', 'FISH', 150, 'Sea', '' ),
( 'Barred Knifejaw', 'FISH', 5000, 'Sea', '' ),
( 'Sea Bass', 'FISH', 400, 'Sea', '' ),
( 'Red Snapper', 'FISH', 3000, 'Sea', '' ),
( 'Dab', 'FISH', 300, '300', '' ),
( 'Olive Flounder', 'FISH', 800, 'Sea', '' ),
( 'Squid', 'FISH', 500, 'Sea', '' ),
( 'Moray Eel', 'FISH', 2000, 'Sea', '' ),
( 'Ribbon Eel', 'FISH', 600, 'Sea', '' ),
( 'Tuna', 'FISH', 7000, 'Pier', '' ),
( 'Blue Marlin', 'FISH', 10000, 'Pier', '' ),
( 'Giant Trevally', 'FISH', 4500, 'Pier', '' ),
( 'Mahi-Mahi', 'FISH', 6000, 'Pier', '' ),
( 'Ocean Sunfish', 'FISH', 4000, 'Sea', '' ),
( 'Ray', 'FISH', 3000, 'Sea', '' ),
( 'Saw Shark', 'FISH', 12000, 'Sea', '' ),
( 'Hammer', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),
( '', 'FISH', 0, '', '' ),

/*    Bugs     */
