/*	
	https://www.ign.com/wikis/animal-crossing-new-horizons/Fish_Guide:_Fish_List,_Sell_Price,_and_Fishing_Tips#Pop-eyed_Goldfish 
	https://www.ign.com/wikis/animal-crossing-new-horizons/Bug_Guide:_Bugs_List,_Sell_Price,_and_Bug_Catching_Tips#Yellow_Butterfly_.E2.9C.93
*/
INSERT INTO [acnh].[Critters]
( [critter_name], [critter_type], [sale_price], [location], [comment] )
VALUES 
( 'Bitterling', 'FISH', 900, 'River', '' ),
( 'Pale Chub', 'FISH', 160, 'River', '' ),
( 'Crucian Carp', 'FISH', 160, 'River', '' ),
( 'Dace', 'FISH', 240, 'River', '' ),
( 'Carp', 'FISH', 300, 'Pond', '' ),
( 'Koi', 'FISH', 4000, 'Pond', '' ),
( 'Goldfish', 'FISH', 1300, 'Pond', '' ),
( 'Pop-eyed Goldfish', 'FISH', 1300, 'Pond', '' ),
( 'Ranchu Goldfish', 'FISH', 4500, 'Pond', '' ),
( 'Killifish', 'FISH', 300, 'Pond', '' ),
( 'Crawfish', 'FISH', 200, 'Pond', '' ),
( 'Soft-shelled Turtle', 'FISH', 3750, 'River', '' ),
( 'Snapping Turtle', 'FISH', 5000, 'River', '' ),
( 'Tadpole', 'FISH', 100, 'Pond', '' ),
( 'Frog', 'FISH', 120, 'Pond', '' ),
( 'Freshwater Goby', 'FISH', 400, 'River', '' ),
( 'Loach', 'FISH', 400, 'River', '' ),
( 'Catfish', 'FISH', 800, 'Pond', '' ),
( 'Giant Snakehead', 'FISH', 5500, 'Pond', '' ),
( 'Bluegill', 'FISH', 180, 'River', '' ),
( 'Yellow Perch', 'FISH', 300, 'River', '' ),
( 'Black Bass', 'FISH', 400, 'River', '' ),
( 'Tilapia', 'FISH', 800, 'River', '' ),
( 'Pike', 'FISH', 1800, 'River', '' ),
( 'Pond Smelt', 'FISH', 0, '400', '' ),
( 'Sweetfish', 'FISH', 900, 'River', '' ),
( 'Cherry Salmon', 'FISH', 1000, 'River (Clifftop)', '' ),
( 'Char', 'FISH', 3800, 'River (Clifftop)', '' ),
( 'Golden Trout', 'FISH', 15000, 'River (Clifftop)', '' ),
( 'Stringfish', 'FISH', 15000, 'River (Clifftop)', '' ),
( 'Salmon', 'FISH', 700, 'River (Mouth)', '' ),
( 'King Salmon', 'FISH', 1800, 'River (Mouth)', '' ),
( 'Mitten Crab', 'FISH', 2000, 'River', '' ),
( 'Guppy', 'FISH', 1300, 'River', '' ),
( 'Nibble Fish', 'FISH', 1500, 'River', '' ),
( 'Angelfish', 'FISH', 3000, 'River', '' ),
( 'Betta', 'FISH', 2500, 'River', '' ),
( 'Neon Tetra', 'FISH', 500, 'River', '' ),
( 'Rainbowfish', 'FISH', 800, 'River', '' ),
( 'Piranha', 'FISH', 2500, 'River', '' ),
( 'Arowana', 'FISH', 10000, 'River', '' ),
( 'Dorado', 'FISH', 15000, 'River', '' ),
( 'Gar', 'FISH', 6000, 'Pond', '' ),
( 'Arapaima', 'FISH', 10000, 'River', '' ),
( 'Saddled Bichir', 'FISH', 4000, 'River', '' ),
( 'Sturgeon', 'FISH', 10000, 'River (Mouth)', '' ),
( 'Sea Butterfly', 'FISH', 1000, 'Sea', '' ),
( 'Seahorse', 'FISH', 1100, 'Sea', '' ),
( 'Clownfish', 'FISH', 650, 'Ocean', '' ),
( 'Sturgeonfish', 'FISH', 1000, 'Sea', '' ),
( 'Butterfly Fish', 'FISH', 1000, 'Sea', '' ),
( 'Napoleonfish', 'FISH', 10000, 'Sea', '' ),
( 'Zebra Turkeyfish', 'FISH', 500, 'Sea', '' ),
( 'Blowfish', 'FISH', 5000, 'Sea', '' ),
( 'Puffer Fish', 'FISH', 250, 'Sea', '' ),
( 'Anchovy', 'FISH', 200, 'Sea', '' ),
( 'Horse Mackerel', 'FISH', 150, 'Sea', '' ),
( 'Barred Knifejaw', 'FISH', 5000, 'Sea', '' ),
( 'Sea Bass', 'FISH', 400, 'Sea', '' ),
( 'Red Snapper', 'FISH', 3000, 'Sea', '' ),
( 'Dab', 'FISH', 300, '300', '' ),
( 'Olive Flounder', 'FISH', 800, 'Sea', '' ),
( 'Squid', 'FISH', 500, 'Sea', '' ),
( 'Moray Eel', 'FISH', 2000, 'Sea', '' ),
( 'Ribbon Eel', 'FISH', 600, 'Sea', '' ),
( 'Tuna', 'FISH', 7000, 'Pier', '' ),
( 'Blue Marlin', 'FISH', 10000, 'Pier', '' ),
( 'Giant Trevally', 'FISH', 4500, 'Pier', '' ),
( 'Mahi-Mahi', 'FISH', 6000, 'Pier', '' ),
( 'Ocean Sunfish', 'FISH', 4000, 'Sea', '' ),
( 'Ray', 'FISH', 3000, 'Sea', '' ),
( 'Saw Shark', 'FISH', 12000, 'Sea', '' ),
( 'Hammerhead Shark', 'FISH', 8000, 'Sea', '' ),
( 'Great White Shark', 'FISH', 15000, 'Sea', '' ),
( 'Whale Shark', 'FISH', 13000, 'Sea', '' ),
( 'Suckerfish', 'FISH', 1500, 'Sea', '' ),
( 'Football Fish', 'FISH', 2500, 'Sea', '' ),
( 'Oarfish', 'FISH', 9000, 'Sea', '' ),
( 'Barreleye', 'FISH', 15000, 'Sea', '' ),
( 'Coelacanth', 'FISH', 15000, 'Sea (Rainy Days)', '' ),


/*    Bugs     */
( 'Common Butterfly', 'BUG', 160, 'FLying above Flowers', '' ),
( 'Yellow Butterfly', 'BUG', 160, 'Flying', '' ),
( 'Tiger Butterfly', 'BUG', 240, 'Flying', '' ),
( 'Peacock Buttefly', 'BUG', 2500, 'Flying above Purple, Black, and Blue Flowers', '' ),
( 'Common Bluebottle', 'BUG', 300, 'Flying', '' ),
( 'Paper Kite Butterfly', 'BUG', 1000, 'Flying', '' ),
( 'Great Purple Emperor', 'BUG', 3000, 'Flying', '' ),
( 'Monarch Butterfly', 'BUG', 140, 'Flying', '' ),
( 'Emperor Butterfly', 'BUG', 4000, 'Flying', '' ),
( 'Agrias Butterfly', 'BUG', 3000, 'Flying', '' ),
( 'Rajah Brooke''s Birdwing', 'BUG', 2500, 'Flying above flowers', '' ),
( 'Queen Alexandra''s Birdwing', 'BUG', 4000, 'Flying', '' ),
( 'Moth', 'BUG', 130, 'Flying around light', '' ),
( 'Atlas Moth', 'BUG', 3000, 'On Trees', '' ),
( 'Madagascan Sunset Moth', 'BUG', 2500, 'Flying', '' ),
( 'Long Locust', 'BUG', 200, 'On the Ground', '' ),
( 'Migratory Locust', 'BUG', 600, 'On the Ground', '' ),
( 'Rice Grasshopper', 'BUG', 160, 'On the Groud', '' ),
( 'Grasshopper', 'BUG', 160, 'On the Ground', '' ),
( 'Cricket', 'BUG', 130, 'On the Ground', '' ),
( 'Bell Cricket', 'BUG', 430, 'On the Ground', '' ),
( 'Mantis', 'BUG', 430, 'On Flowers', '' ),
( 'Orchid Mantis', 'BUG', 2400, 'On Flowers (White)', '' ),
( 'Honeybee', 'BUG', 200, 'Flying above Flowers', '' ),
( 'Wasp', 'BUG', 2500, 'Shaking Trees', '' ),
( 'Brown Cicada', 'BUG', 250, 'On Trees', '' ),
( 'Robust Cicada', 'BUG', 300, 'On Trees', '' ),
( 'Giant Cicada', 'BUG', 500, 'On Trees', '' ),
( 'Walker Cicada', 'BUG', 400, 'On Trees', '' ),
( 'Evening Cicada', 'BUG', 550, 'On Trees', '' ),
( 'Cicada Shell', 'BUG', 10, 'On Trees', '' ),
( 'Red Dragonfly', 'BUG', 180, 'Flying', '' ),
( 'Darner Dragonfly', 'BUG', 230, 'Flying', '' ),
( 'Banded Dragonfly', 'BUG', 4500, 'Flying', '' ),
( 'Damselfly', 'BUG', 500, 'Flying', '' ),
( 'Firefly', 'BUG', 300, 'Flying', '' ),
( 'Mole Cricket', 'BUG', 500, 'Underground', '' ),
( 'Pondskater', 'BUG', 130, 'On Ponds and Rivers', '' ),
( 'Diving Beetle', 'BUG', 800, 'On Ponds and Rivers', '' ),
( 'Giant Water Bug', 'BUG', 2000, 'On Ponds and Rivers', '' ),
( 'Stinkbug', 'BUG', 120, 'On Flowers', '' ),
( 'Man-faced Stink Bug', 'BUG', 1000, 'On Flowers', '' ),
( 'Ladybug', 'BUG', 200, 'On Flowers', '' ),
( 'Tiger Beetle', 'BUG', 1500, 'Flying', '' ),
( 'Jewel Beetle', 'BUG', 2400, 'On Tree Stumps', '' ),
( 'Citrus Long-Horned Beetle', 'BUG', 350, 'On Tree Stumps', '' ),
( 'Rosalia Batesi Beetle', 'BUG', 3000, 'On Tree Stumps', '' ),
( 'Blue Weevil Beetle', 'BUG', 800, 'On Trees', '' ),
( 'Violin Beetle', 'BUG', 450, 'On Trees', '' ),
( 'Dung Beetle', 'BUG', 3000, 'On the Ground (Rolling Snowballs)', '' ),
( 'Earth-boring Dung Beetle', 'BUG', 300, 'On Ground', '' ),
( 'Scarab Beetle', 'BUG', 10000, 'On Trees', '' ),
( 'Drone Beetle', 'BUG', 200, 'On Trees', '' ),
( 'Goliath Beetle', 'BUG', 8000, 'On Trees (Coconut)', '' ),
( 'Saw Stag', 'BUG', 2000, 'On Trees', '' ),
( 'Miyama Stag', 'BUG', 1000, 'On Trees', '' ),
( 'Giant Stag', 'BUG', 10000, 'On Trees', '' ),
( 'Rainbow Stag', 'BUG', 6000, 'On Trees', '' ),
( 'Cyclommatus Stag', 'BUG', 8000, 'On Trees', '' ),
( 'Golden Stag', 'BUG', 12000, 'On Trees', '' ),
( 'Giraffe Stag', 'BUG', 12000, 'On Trees', '' ),
( 'Horned Dynastid', 'BUG', 1350, 'On Trees', '' ),
( 'Horned Atlas', 'BUG', 8000, 'On Trees', '' ),
( 'Horned Elephant', 'BUG', 8000, 'On Trees', '' ),
( 'Horned Hercules', 'BUG', 12000, 'On Trees', '' ),
( 'Walking Stick', 'BUG', 600, 'On Trees', '' ),
( 'Walking Leaf', 'BUG', 600, 'On Ground (Beneath Trees)', '' ),
( 'Bagworm', 'BUG', 600, 'Shaking Trees', '' ),
( 'Ant', 'BUG', 80, 'On Rotten Turnips and Fruit', '' ),
( 'Hermit Crab', 'BUG', 1000, 'On Beach', '' ),
( 'Wharf Roach', 'BUG', 200, 'On Beach (Rocks)', '' ),
( 'Fly', 'BUG', 60, 'On Rotten Food and Garbage', '' ),
( 'Mosquito', 'BUG', 130, 'Flying', '' ),
( 'Flea', 'BUG', 70, 'On Flea-Infested Villagers', '' ),
( 'Snail', 'BUG', 250, 'On Rocks (During Rain)', '' ),
( 'Pill Bug', 'BUG', 250, 'Hitting Rocks', '' ),
( 'Centipede', 'BUG', 300, 'Hitting Rocks', '' ),
( 'Spider', 'BUG', 480, 'Shaking Trees', '' ),
( 'Tarantula', 'BUG', 8000, 'On Ground', '' ),
( 'Scorpion', 'BUG', 8000, 'On Ground', '' )