INSERT INTO [common].[People]
( [person_first_name], [person_last_name], [person_relationship] )
VALUES
('Nik', 'Bournelis', ''),
('Ian', 'Bournelis', ''),
('Andrew', 'Schock', ''),
('Sean', 'Stengel', ''),
('Stephen', 'Hausler', ''),
('Whitney', 'Weinstein', ''),
('Michael', 'Hains', ''),
('Chris', 'Wozunk', ''),
('Abby', '', 'Wozunk''s girlfriend (at the time)'),
('Mike', 'LeCastre', ''),
('Anita', '', 'Mike LeCastre''s girlfriend'),
('Sean', 'Flynn', ''),
('Cathy', 'Kaing', ''),
('Veronika', 'Legobitova', ''),
('Kevin', 'Boensch', ''),
('Mike', 'Shinbrot', ''),
('Katie', 'Schock', ''),
('Monica', 'Lee', ''),
('Rob', 'Hausler', ''),
('Tevin', 'Hill', ''),
('Steve', 'DiPietro', ''),
('Chris', 'Seidl', ''),
('Jon', 'Bean', ''),
('Amanda', 'Ondash', ''),
('Andrew', 'Good', ''),
('Tim', 'Chua', ''),
('Mem', '', ''),
('Chrysan', 'Bournelis', ''),
('Jim', 'Bournelis', ''),
('Roy', '', 'Mike Shinbrot''s friend'),
('Sunil', 'Verma', ''),
('Alex', 'Abadiotakis', ''),
('Erica', 'Henn', ''),
('Nola', 'McAloon', ''),
('Steph', 'Kovacs', ''),
('Joey', 'Painter', ''),
('Mike', 'Batson', 'Steve DiPietro''s cousin'),
('Greta', 'Ertzgard', ''),
('Stephan', '', 'Veronika''s husband'),
('Sean', 'Harrington', ''),
('Christine', 'Kantonides', ''),
('Ian', 'Kerrington', 'Whitney'' friend'),
('Duncan', '', 'Met through Ian and Whitney'),
('John', 'Sinis', 'Met through Ian and Whitney'),
('Tim', '', 'Duncan''s friend from childhood, Met through Ian and Whitney'),
('Will', '', 'Met through Ian and Whitney'),
('Grace', '', 'Will''s sister, met through Ian and Whitney'),
('Eric', '', 'Grace''s boyfriend'),
('Dave', '', 'Ian K''s friend'),
('Anna', '', 'Dave''s girlfriend')