//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnualAward
    {
        public AnnualAward()
        {
            this.AnnualAwardMemberXREFs = new HashSet<AnnualAwardMemberXREF>();
        }
    
        public int award_id { get; set; }
        public string award_title { get; set; }
        public string award_description { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime last_modified { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual ICollection<AnnualAwardMemberXREF> AnnualAwardMemberXREFs { get; set; }
    }
}
