//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnualAwardMemberXREF
    {
        public int award_id { get; set; }
        public int member_id { get; set; }
        public int year_awarded { get; set; }
    
        public virtual AnnualAward AnnualAward { get; set; }
        public virtual Member Member { get; set; }
    }
}
