//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Band
    {
        public Band()
        {
            this.ConcertSong_xref = new HashSet<ConcertSong_xref>();
            this.Concerts = new HashSet<Concert>();
        }
    
        public int band_id { get; set; }
        public string band_name { get; set; }
    
        public virtual ICollection<ConcertSong_xref> ConcertSong_xref { get; set; }
        public virtual ICollection<Concert> Concerts { get; set; }
    }
}
