//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class concertContext : DbContext
    {
        public concertContext()
            : base("name=concertContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Band> Bands { get; set; }
        public virtual DbSet<Concert> Concerts { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Venue> Venues { get; set; }
        public virtual DbSet<ConcertSong_xref> ConcertSong_xref { get; set; }
    }
}
