//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concert
    {
        public Concert()
        {
            this.ConcertSong_xref = new HashSet<ConcertSong_xref>();
            this.Bands = new HashSet<Band>();
            this.People = new HashSet<Person>();
        }
    
        public int concert_id { get; set; }
        public Nullable<int> ticket_price { get; set; }
        public System.DateTime concert_date { get; set; }
        public string concert_day_of_week { get; set; }
        public int venue_id { get; set; }
        public string comment { get; set; }
    
        public virtual Venue Venue { get; set; }
        public virtual ICollection<ConcertSong_xref> ConcertSong_xref { get; set; }
        public virtual ICollection<Band> Bands { get; set; }
        public virtual ICollection<Person> People { get; set; }
    }
}
