//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcertSong_xref
    {
        public int concert_id { get; set; }
        public int band_id { get; set; }
        public string song_title { get; set; }
        public string comment { get; set; }
    
        public virtual Band Band { get; set; }
        public virtual Concert Concert { get; set; }
    }
}
