//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailListing
    {
        public string email_address { get; set; }
        public int member_id { get; set; }
        public System.DateTime date_added { get; set; }
        public Nullable<System.DateTime> date_removed { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
