//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighZetaPosition
    {
        public HighZetaPosition()
        {
            this.MemberHighZetaPositionXREFs = new HashSet<MemberHighZetaPositionXREF>();
        }
    
        public int position_id { get; set; }
        public string position_name { get; set; }
        public string position_description { get; set; }
    
        public virtual ICollection<MemberHighZetaPositionXREF> MemberHighZetaPositionXREFs { get; set; }
    }
}
