//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseManagerResourceInfo
    {
        public string resource_name { get; set; }
        public string resource_type { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }
        public string comment { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime last_modified { get; set; }
        public bool is_deleted { get; set; }
    }
}
