//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportantEvent
    {
        public int event_id { get; set; }
        public string event_title { get; set; }
        public string event_description { get; set; }
        public Nullable<System.DateTime> event_date { get; set; }
        public Nullable<int> member_poc_id { get; set; }
        public int event_added_by_member_id { get; set; }
        public System.DateTime date_added { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
    }
}
