//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LambdaChiAlphaContext : DbContext
    {
        public LambdaChiAlphaContext()
            : base("name=LambdaChiAlphaContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlumniBoard> AlumniBoards { get; set; }
        public virtual DbSet<AnnualAward> AnnualAwards { get; set; }
        public virtual DbSet<HighZetaPosition> HighZetaPositions { get; set; }
        public virtual DbSet<InitiationClass> InitiationClasses { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<AlumniBoardMemberXREF> AlumniBoardMemberXREFs { get; set; }
        public virtual DbSet<AlumniReportMeetingMinute> AlumniReportMeetingMinutes { get; set; }
        public virtual DbSet<AnnualAwardMemberXREF> AnnualAwardMemberXREFs { get; set; }
        public virtual DbSet<ChangeHistory> ChangeHistories { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<EmailListing> EmailListings { get; set; }
        public virtual DbSet<EmergencyContact> EmergencyContacts { get; set; }
        public virtual DbSet<HouseManagerResourceInfo> HouseManagerResourceInfoes { get; set; }
        public virtual DbSet<ImportantEvent> ImportantEvents { get; set; }
        public virtual DbSet<LXAAddressesRaw> LXAAddressesRaws { get; set; }
        public virtual DbSet<LXAAddressesRaw_GoldCopy> LXAAddressesRaw_GoldCopy { get; set; }
        public virtual DbSet<MemberContactInformation> MemberContactInformations { get; set; }
        public virtual DbSet<MemberHighZetaPositionXREF> MemberHighZetaPositionXREFs { get; set; }
        public virtual DbSet<OutOfDateMemberAddress> OutOfDateMemberAddresses { get; set; }
        public virtual DbSet<OutOfDateMemberEmail> OutOfDateMemberEmails { get; set; }
        public virtual DbSet<OutOfDateMemberPhoneNumber> OutOfDateMemberPhoneNumbers { get; set; }
    }
}
