//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LXAAddressesRaw_GoldCopy
    {
        public int id { get; set; }
        public string grad_year { get; set; }
        public string drexel_grad_year { get; set; }
        public string ek_number { get; set; }
        public string date_of_death { get; set; }
        public string date_of_birth { get; set; }
        public string date_of_initiation { get; set; }
        public string full_name { get; set; }
        public string work_1 { get; set; }
        public string major { get; set; }
        public string wife { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string preferred_email { get; set; }
        public string email_1 { get; set; }
        public string email_2 { get; set; }
        public string email_3 { get; set; }
        public string status { get; set; }
        public string address { get; set; }
        public string apt_1 { get; set; }
        public string city_1 { get; set; }
        public string state_1 { get; set; }
        public string zip_1 { get; set; }
        public string phone_1 { get; set; }
        public string phone_2 { get; set; }
        public string mobile { get; set; }
        public string home { get; set; }
        public string work_2 { get; set; }
        public string xxx_1 { get; set; }
        public string bad_email_address_1 { get; set; }
        public string bad_email_address_2 { get; set; }
        public string bad_email_address_3 { get; set; }
        public string xxx_2 { get; set; }
        public string street { get; set; }
        public string apt_2 { get; set; }
        public string city_2 { get; set; }
        public string state_2 { get; set; }
        public string zip_2 { get; set; }
        public string xxx_3 { get; set; }
        public string bad_street { get; set; }
        public string bad_apt { get; set; }
        public string bad_city { get; set; }
        public string bad_state { get; set; }
        public string bad_zip { get; set; }
        public string xxx_4 { get; set; }
        public string grad_year_sorting { get; set; }
        public string date_of_death_sorting { get; set; }
        public string date_of_birth_sorting { get; set; }
        public string date_of_initiation_sorting { get; set; }
        public string ek_number_sorting { get; set; }
    }
}
