//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.InitiationClasses = new HashSet<InitiationClass>();
            this.AlumniBoardMemberXREFs = new HashSet<AlumniBoardMemberXREF>();
            this.AnnualAwardMemberXREFs = new HashSet<AnnualAwardMemberXREF>();
            this.ChangeHistories = new HashSet<ChangeHistory>();
            this.EmailListings = new HashSet<EmailListing>();
            this.EmergencyContacts = new HashSet<EmergencyContact>();
            this.ImportantEvents = new HashSet<ImportantEvent>();
            this.ImportantEvents1 = new HashSet<ImportantEvent>();
            this.MemberContactInformations = new HashSet<MemberContactInformation>();
            this.MemberHighZetaPositionXREFs = new HashSet<MemberHighZetaPositionXREF>();
            this.OutOfDateMemberAddresses = new HashSet<OutOfDateMemberAddress>();
            this.OutOfDateMemberEmails = new HashSet<OutOfDateMemberEmail>();
            this.OutOfDateMemberPhoneNumbers = new HashSet<OutOfDateMemberPhoneNumber>();
            this.Members1 = new HashSet<Member>();
            this.Members = new HashSet<Member>();
        }
    
        public int member_id { get; set; }
        public string member_first_name { get; set; }
        public string member_last_name { get; set; }
        public string member_type { get; set; }
        public string year { get; set; }
        public Nullable<int> graduation_year { get; set; }
        public string masters { get; set; }
        public string major { get; set; }
        public string minor { get; set; }
        public string zeta_associated { get; set; }
        public string zeta_number { get; set; }
        public Nullable<int> zeta_number_sorting { get; set; }
        public int initiation_class_id { get; set; }
        public Nullable<int> big_brother_id { get; set; }
        public string member_status { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public Nullable<System.DateTime> date_of_death { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime last_modified { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual ICollection<InitiationClass> InitiationClasses { get; set; }
        public virtual InitiationClass InitiationClass { get; set; }
        public virtual ICollection<AlumniBoardMemberXREF> AlumniBoardMemberXREFs { get; set; }
        public virtual ICollection<AnnualAwardMemberXREF> AnnualAwardMemberXREFs { get; set; }
        public virtual ICollection<ChangeHistory> ChangeHistories { get; set; }
        public virtual ICollection<EmailListing> EmailListings { get; set; }
        public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; }
        public virtual ICollection<ImportantEvent> ImportantEvents { get; set; }
        public virtual ICollection<ImportantEvent> ImportantEvents1 { get; set; }
        public virtual ICollection<MemberContactInformation> MemberContactInformations { get; set; }
        public virtual ICollection<MemberHighZetaPositionXREF> MemberHighZetaPositionXREFs { get; set; }
        public virtual ICollection<OutOfDateMemberAddress> OutOfDateMemberAddresses { get; set; }
        public virtual ICollection<OutOfDateMemberEmail> OutOfDateMemberEmails { get; set; }
        public virtual ICollection<OutOfDateMemberPhoneNumber> OutOfDateMemberPhoneNumbers { get; set; }
        public virtual ICollection<Member> Members1 { get; set; }
        public virtual ICollection<Member> Members { get; set; }
    }
}
