//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Concerts = new HashSet<Concert>();
        }
    
        public int person_id { get; set; }
        public string person_first_name { get; set; }
        public string person_last_name { get; set; }
        public string person_relationship { get; set; }
    
        public virtual ICollection<Concert> Concerts { get; set; }
    }
}
