//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public Venue()
        {
            this.Concerts = new HashSet<Concert>();
        }
    
        public int venue_id { get; set; }
        public string venue_name { get; set; }
        public string venue_city { get; set; }
        public string venue_state { get; set; }
        public string comment { get; set; }
    
        public virtual ICollection<Concert> Concerts { get; set; }
    }
}
