INSERT INTO concerts.Bands
( band_name )
VALUES
( 'Green Day' ),
( 'The Bravery' ),
( 'AFI' ),
( 'Blink-182' ),
( 'My Chemical Romance' ),
( 'Rise Against' ),
( 'A Day To Remember' ),
( 'Jimmy Eat World' ),
( 'All American Rejects' ),
( 'Motion City Soundtrack' ),
( 'Foo Fighters' ),
( 'Macklemore' ),
( 'Yellowcard' ),
( 'Sum 41' ),
( 'Goo Goo Dolls' ),
( 'Matchbox Twenty' ),
( 'Bruce Springsteen' ),
( 'Arctic Monkeys' ),
( 'Cheap Trick' ),
( 'Paul McCartney' ),
( 'Royal Blood' ),
( 'Marilyn Manson' ),
( 'Smashing Pumpkins' ),
( 'Hawthorne Heights' ),
( 'Dave Matthews Band' ),
( 'PANIC! At the Disco' ),
( 'Weezer' ),
( 'Andrew McMahon in the Wilderness' ),
( 'Modest Mouse' ),
( 'Brand New' ),
( 'Dog Party' ),
( 'Red Hot Chili Peppers' ),
( 'Against Me!' ),
( 'Tom Petty and the Heartbreakers' ),
( 'Joan Jett and the Blackhearts' ),
( 'Heart' ),
( 'Animal Collective' ),
( 'Foreigner' ),
( 'Gorillaz' ),
( 'Linkin Park' ),
( 'Fleet Foxes' ),
( 'Peter Frampton' ),
( 'Dave Matthews and Tim Reynolds' ),
( 'Boston' ),
( 'Arcade Fire' )
