INSERT INTO [concerts].[Venues]
( [venue_name], [venue_city], [venue_state] )
VALUES 
( 'Wachovia Spectrum', 'Philadelphia', 'PA' ),
( 'Susquehanna Bank Center', 'Camden', 'NJ' ),
( 'Hershey Stadium', 'Hershey', 'PA' ),
( 'Bamboozle', 'Asbury Park', 'NJ' ),
( 'Theater of the Living Arts', 'Philadelphia', 'PA' ),
( 'Electric Factory', 'Philadelphia', 'PA' ),
( 'Chameleon Club', 'Lancaster', 'PA' ),
( 'Liacouras Center', 'Philadelphia', 'PA' ),
( 'Sands Bethlehem Center', 'Bethlehem', 'PA' ),
( 'Firefly', 'Dover', 'DE' ),
( 'Red Rocks Amphitheatre', 'Morrison', 'CO' ),
( 'Wells Fargo Center', 'Philadelphia', 'PA' ),
( 'Fiddler''s Green Amphitheatre', 'Englewood', 'CO' ),
( 'Tower Theater', 'Philadelphia', 'PA' ),
( 'BB&T Center', 'Camden', 'NJ' ),
( 'Citizen''s Bank Park', 'Philadelphia', 'PA' ),
( 'The Mann Center', 'Philadelphia', 'PA' ),
( 'Atlantic City Beach', 'Atlantic City', 'NJ' ),
( '1stBANK Center', 'Broomfield', 'CO' ),
( 'GIANT Center', 'Hershey', 'PA' ),
( 'Festival Pier Plaza', 'Philadelphia', 'PA' ),
( 'Fillmore Theater', 'Philadelphia', 'PA' )
