//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumniReportMeetingMinute
    {
        public System.DateTime alumni_meeting_date { get; set; }
        public string file_location { get; set; }
        public System.DateTime date_added { get; set; }
        public bool is_deleted { get; set; }
    }
}
