//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumniBoardMemberXREF
    {
        public int board_id { get; set; }
        public int member_id { get; set; }
        public string board_role { get; set; }
        public Nullable<System.DateTime> term_start_date { get; set; }
        public Nullable<System.DateTime> term_end_date { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime last_modified { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual AlumniBoard AlumniBoard { get; set; }
        public virtual Member Member { get; set; }
    }
}
