//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InitiationClass
    {
        public InitiationClass()
        {
            this.Members = new HashSet<Member>();
        }
    
        public int initiation_class_id { get; set; }
        public string initiation_class { get; set; }
        public System.DateTime initiation_date { get; set; }
        public Nullable<int> e_member_id { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime last_modified { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual ICollection<Member> Members { get; set; }
    }
}
