//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberHighZetaPositionXREF
    {
        public int member_id { get; set; }
        public int position_id { get; set; }
        public string term { get; set; }
        public int year { get; set; }
        public bool is_active { get; set; }
    
        public virtual HighZetaPosition HighZetaPosition { get; set; }
        public virtual Member Member { get; set; }
    }
}
