//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberContactInformation
    {
        public int member_id { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }
        public string mailing_street_address { get; set; }
        public string mailing_county { get; set; }
        public string mailing_state { get; set; }
        public string mailing_zip { get; set; }
        public string mailing_country { get; set; }
        public string comment { get; set; }
        public bool send_email { get; set; }
        public bool send_physical_mail { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime last_modified { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
